version: 2

jobs:
  deploy_redoc:
    docker:
      - image: circleci/node:11.1.0

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:fc:61:7b:d4:b0:86:22:e4:71:8c:df:23:71:19:ce"
      - run:
          name: Keyscan deploy server
          command: ssh-keyscan -p 1234 -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

      - run:
          name: Deploy
          command: |
            ssh -p 1234 life@$DEPLOY_SERVER 'cd ~/hackuniversity_logistic && git pull && cd redoc && docker-compose up -d --build'


workflows:
  version: 2
  hackuniversity_deploy:
    jobs:
      - deploy_redoc